city1x          dw 0
city1y          dw -22
city1h          dw 21
city1           db 8 dup(1),0,7,7,7,0,5 dup(7fh),80h,-1,1fh

city2x          dw 8
city2y          dw -22
city2h          dw 22
city2           db 8 dup(0fch),0,-1,-1,-1,1eh,5 dup(0eeh),10h,-1,-1,-1

city3x          dw 16
city3y          dw -27
city3h          dw 28
city3           db 13 dup(7fh),3fh,0dfh,0dfh,0,7 dup(0ffh),0,-1,-1,-1

city4x          dw 24
city4y          dw -32
city4h          dw 33
city4           db 10 dup(7),0,10 dup(7fh),3fh,7 dup(0dfh),20h,-1,-1,-1

city5x          dw 32
city5y          dw -32
city5h          dw 33
city5           db 10 dup(0fch),7ch,0bch,0b0h,7 dup(0afh),0ach,7 dup(0abh),93h,7ch,-1,-1,-1

city6x          dw 40
city6y          dw -23
city6h          dw 24
city6           db 3 dup(1fh),3,7 dup(0fdh),0,8 dup(-1),0,-1,-1,-1

city7x          dw 48
city7y          dw -23
city7h          dw 23
city7           db 4 dup(0f8h),0c0h,4 dup(0bfh),0beh,0beh,1eh,7 dup(0eeh),0e1h,1fh,-1,-1

city8x          dw 56
city8y          dw -18
city8h          dw 17
city8           db 3 dup(0e0h),0,10 dup(0feh),1,-1,0f8h

missile         db 10h,10h,38h,38h,38h,38h,7ch,0feh





